apiVersion: v1
kind: Service
metadata:
  name: service-backend
  labels:
    app: qlas
    type: backend
spec:
  type: NodePort
  selector:
    type: backend
  ports:
    - port: 2017
      targetPort: 2017
      nodePort: 30012