apiVersion: v1
kind: Service
metadata:
  name: service-frontend
  labels:
    app: qlas
    type: frontend
spec:
  type: LoadBalancer
  selector:
    type: frontend
  ports:
    - port: 8080
      targetPort: 80
      nodePort: 30013